### PR TITLE
Add JSON serialize/deserialize support for JavaScript

### PR DESCRIPTION
**Pull request by aslakhellesoy**
### 🤔 What's changed?

Added the ability to serialize/deserailize `ParameterTypeRegistry`, `ParameterType`, `CucumberExpression` and `RegularExpression` to/from JSON.

### ⚡️ What's your motivation? 

In order to complete https://github.com/cucumber/vscode/pull/81 we need to have a copy of the parameter types and expressions running in a browser environment. This is because VSCode custom renderers run in an iframe inside VSCode.

This means we have to take all of the Cucumber expressions that are loaded into the language server, and serialize them into JSON. The HTML page then needs to deserialize them.

I'm making this a draft until https://github.com/cucumber/vscode/pull/81 is ready to be merged.

### 🏷️ What kind of change is this?

- :zap: New feature (non-breaking change which adds new behaviour)

### 📋 Checklist:

- [x] I agree to respect and uphold the [Cucumber Community Code of Conduct](https://cucumber.io/conduct/)
- [ ] I've changed the behaviour of the code
  - [ ] I have added/updated tests to cover my changes.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly.
- [ ] Users should know about my change
  - [ ] I have added an entry to the "Unreleased" section of the [**CHANGELOG**](../CHANGELOG.md), linking to this pull request.

----

*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/PULL_REQUEST_TEMPLATE.md)*

### CODE REVIEW

**Comment by mpkorstanje** [comment]
I would expect the conversion to/from json to be handled outside of this library. It's purely a concern between the language server and blocky. Though I don't know enough to say where exactly it should sit.

Making the information needed to perform serialization (e.g `builtin`) accessible is fine.

**Comment by aslakhellesoy** [comment]
The way custom JSON serialization is handled in JavaScript is to [override toJSON](https://futurestud.io/tutorials/create-a-custom-tojson-function-in-node-js-and-javascript). Custom serialization cannot be done easily by an outside library.

So in order to serialize these objects, those `toJSON` methods have to be defined here.

Technically, the `ExpressionFactory#createExpressionFromJson` and `ParameterTypeRegistry.fromJSON()` methods could be left out of this library. Still, I'd prefer to leave them in as it provides a more cohesive serialization/deserialization API.

**Comment by mpkorstanje** [comment]
Okay, then consider the idea of not serializing any objects from this library at all. Rather map them to some message object and serialize and deserialize the message and then map the message back. While more complicated it keeps a one-of concern out of this library.

**Comment by aslakhellesoy** [comment]
I've removed all the custom serialization logic as suggested by @mpkorstanje. I've left `builtin` in, as it makes it possible to filter out built-in types before serializing custom types.

**Pull request merged**
