### PR TITLE
Feature/enable transformer capture

### PR DESCRIPTION
**Pull request by luke-hill**
### 🤔 What's changed?

Expose `transformer` arg on `ParameterType`.

### ⚡️ What's your motivation? 

 Needed for CCK conformancy (v12/v13) for cucumber-ruby. We need to store the `SourceLocation` proc for the `ParameterType`, this is currently not possible.

### 🏷️ What kind of change is this?

- :zap: New feature (non-breaking change which adds new behaviour)
- :boom: Breaking change (incompatible changes to the API)

### 📋 Checklist:

- [x] I agree to respect and uphold the [Cucumber Community Code of Conduct](https://cucumber.io/conduct/)
- [ ] I've changed the behaviour of the code
  - [ ] I have added/updated tests to cover my changes.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly.
- [ ] Users should know about my change
  - [ ] I have added an entry to the "Unreleased" section of the [**CHANGELOG**](../blob/main/CHANGELOG.md), linking to this pull request.

----

*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/PULL_REQUEST_TEMPLATE.md)*

### CODE REVIEW

**Comment by mpkorstanje** [comment]
> Needed for CCK conformancy (v12/v13) for cucumber-ruby

@luke-hill could you elaborate on this? For the CCK I would expect `transform` would be sufficient.

**Comment by luke-hill** [comment]
Sure. Basically we don't have this reader. So this reader will enable us to grab the transformer proc. Specifically it's `SourceLocation`

This is what the other languages do I believe, but it wasn't present in ruby. This will now enable us to use v12/v13 cck and fix up the final hard-coded bit of logic in the CCK conformancy PR.

**Comment by mpkorstanje** [comment]
Check, looks like Java is the exception here (no easy way to get a source location). So that makes sense. See it's public in JS too.

**Review by mpkorstanje — APPROVED** [review]

**Comment by luke-hill** [comment]
Out of curiousity. How do you conform to the CCK that stipulates you need a `SourceLocation` for the `ParameterType` in java then? Requested here: https://github.com/cucumber/cucumber-jvm/pull/2739/files

**Comment by mpkorstanje** [comment]
Cucumber-JVM doesn't expose the API from Cucumber Expressions to the end user. So instead of having the user register a parameter type, they annotate a method and Cucumber JVM maps that annotated method to a parameter type and registers it. The messages are then created based on the parameter type registered and the source location of the annotated method.

**Pull request merged**
