### PR TITLE
Help ESLint understand monorepo paths

### PR DESCRIPTION
**Pull request by mattwynne**
I found that, when using VSCode with the whole repo open, ESLint couldn't find the tsconfig file.

This seems to have fixed it.

### CODE REVIEW

**Comment by mattwynne** [comment]
Well, I guess _that_ didn't work...

**Comment by aurelien-reeves** [comment]
It would be great to fix that VSCode issue indeed

However I don't understand how the patch could work: that new `.eslintrc.json` file in the root folder seems to refer to an unexistant `tsconfig.json` file in the root folder too 🤔

**Comment by mattwynne** [comment]
> It would be great to fix that VSCode issue indeed
> 
> However I don't understand how the patch could work: that new `.eslintrc.json` file in the root folder seems to refer to an unexistant `tsconfig.json` file in the root folder too 🤔

Yeah, I thought it did work yesterday but it doesn't today! I think I may have another commit that fixes it...

**Comment by aurelien-reeves** [comment]
I think the issue is not related to the project itself, but to the IDE.
I have pushed a proposal more related to the IDE than the project.
What do you think all?

**Comment by mattwynne** [comment]
Ooh nice one! I'll give that a try.

**Comment by aslakhellesoy** [comment]
What's going on with this PR? I don't use VSCode so I don't have much to offer. Except that I think repos shouldn't contain editor-specific configurations.

**Comment by aurelien-reeves** [comment]
@aslakhellesoy if you agree with having IDE config file within the repo as suggested by this PR, we can merge. If not, we could just close it :)

**Comment by aurelien-reeves** [comment]
> Except that I think repos shouldn't contain editor-specific configurations.

**Pull request closed without merging**
